### ISSUE TITLE
Chat messages sent from the "rcon_chat_channel" channel should not be sent as ADMIN

### ISSUE THREAD

**Issue by hlyl** [schana/carim-discord-bot#4]
Today the messages sent from the "rcon_chat_channel" Channel are sent with the admin "tag"
It would be optimal if this was only used for the 
"rcon_admin_channels"

and chat from the  "rcon_chat_channel" was only sent as a message to the server.

**Comment by schana** [comment]
This seems to be an artifact of the chat mod you're using. For vanilla game chat, messages from discord look like:
![image](https://user-images.githubusercontent.com/9595417/78553888-5a681c80-780a-11ea-83bd-b7ed10ea412f.png)

The messages coming from the bot are being sent from an RCon Admin, and there is no current way in the protocol to specify otherwise.
